// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mortgage.Ecosystem.DataAccess.Layer.Models;

#nullable disable

namespace Mortgage.Ecosystem.DataAccess.Layer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230524225959_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.AccountTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_AccountType", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.AgentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_AgentType", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.AlertTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_AlertType", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.AutoJobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("CronExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_AutoJob", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.AutoJobLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<string>("JobGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LogStatus")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_AutoJobLog", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.BankEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_Bank", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.BranchEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Location");

                    b.Property<long>("Manager")
                        .HasColumnType("bigint")
                        .HasColumnName("Manager");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MobileNumber");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nationality");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.ToTable("tbl_Branch", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.CompanyClassEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_CompanyClass", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.CompanyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<int>("CompanyClass")
                        .HasColumnType("int")
                        .HasColumnName("CompanyClass");

                    b.Property<int>("CompanyType")
                        .HasColumnType("int")
                        .HasColumnName("CompanyType");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContactPerson");

                    b.Property<int>("ContactPersonDesignation")
                        .HasColumnType("int")
                        .HasColumnName("ContactPersonDesignation");

                    b.Property<int>("ContributionFrequency")
                        .HasColumnType("int")
                        .HasColumnName("ContributionFrequency");

                    b.Property<DateTime?>("DateOfCommencement")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfCommencement");

                    b.Property<DateTime?>("DateOfIncorporation")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfIncorporation");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fax");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Logo");

                    b.Property<string>("LogoType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogoType");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MobileNumber");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("NameOfRegistrar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NameOfRegistrar");

                    b.Property<string>("NameOfTrustees")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NameOfTrustees");

                    b.Property<string>("NatureOfBusiness")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NatureOfBusiness");

                    b.Property<string>("RCNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RCNumber");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark");

                    b.Property<int>("Sector")
                        .HasColumnType("int")
                        .HasColumnName("Sector");

                    b.Property<int>("Subsector")
                        .HasColumnType("int")
                        .HasColumnName("Subsector");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Website");

                    b.HasKey("Id");

                    b.ToTable("tbl_Company", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.CompanyTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_CompanyType", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.ContributionFrequencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_ContributionFrequency", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.DepartmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<long?>("Branch")
                        .HasColumnType("bigint")
                        .HasColumnName("Branch");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fax");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<long?>("Principal")
                        .HasColumnType("bigint")
                        .HasColumnName("Principal");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("Sort");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telephone");

                    b.HasKey("Id");

                    b.ToTable("tbl_Department", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.DesignationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("Sort");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("st_Designation", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.EmployeeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("AccountType")
                        .HasColumnType("int")
                        .HasColumnName("AccountType");

                    b.Property<int>("AlertType")
                        .HasColumnType("int")
                        .HasColumnName("AlertType");

                    b.Property<string>("BVN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BVN");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BankAccountNumber");

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<long>("Branch")
                        .HasColumnType("bigint")
                        .HasColumnName("Branch");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<string>("CustomerBank")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CustomerBank");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("DateOfEmployment")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfEmployment");

                    b.Property<int>("Department")
                        .HasColumnType("int")
                        .HasColumnName("Department");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentType");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int")
                        .HasColumnName("MaritalStatus");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MobileNumber");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MonthlySalary");

                    b.Property<string>("NIN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NIN");

                    b.Property<string>("OtherName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OtherName");

                    b.Property<byte[]>("Portrait")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Portrait");

                    b.Property<string>("PortraitType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PortraitType");

                    b.Property<string>("PostalAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostalAddress");

                    b.Property<string>("StaffNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StaffNumber");

                    b.Property<int>("Title")
                        .HasColumnType("int")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("tbl_Employee", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.GenderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_Gender", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.LogLoginEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Browser");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<string>("ExtraRemark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraRemark");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IpAddress");

                    b.Property<string>("IpLocation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IpLocation");

                    b.Property<int>("LogStatus")
                        .HasColumnType("int")
                        .HasColumnName("LogStatus");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OS");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark");

                    b.HasKey("Id");

                    b.ToTable("tbl_LogLogin", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.LogOperateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<string>("BusinessType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BusinessType");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<string>("ExecuteParam")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExecuteParam");

                    b.Property<string>("ExecuteResult")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExecuteResult");

                    b.Property<int>("ExecuteTime")
                        .HasColumnType("int")
                        .HasColumnName("ExecuteTime");

                    b.Property<string>("ExecuteUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExecuteUrl");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IpAddress");

                    b.Property<string>("IpLocation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IpLocation");

                    b.Property<int>("LogStatus")
                        .HasColumnType("int")
                        .HasColumnName("LogStatus");

                    b.Property<string>("LogType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogType");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark");

                    b.HasKey("Id");

                    b.ToTable("tbl_LogOperate", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.MaritalStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_MaritalStatus", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.MenuAuthorizeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("AuthorizeId")
                        .HasColumnType("bigint")
                        .HasColumnName("AuthorizeId");

                    b.Property<int>("AuthorizeType")
                        .HasColumnType("int")
                        .HasColumnName("AuthorizeType");

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("MenuId");

                    b.HasKey("Id");

                    b.ToTable("tbl_MenuAuthorize", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.MenuEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalLevel");

                    b.Property<int>("Approved")
                        .HasColumnType("int")
                        .HasColumnName("Approved");

                    b.Property<string>("Authorize")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Authorize");

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MenuIcon");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MenuName");

                    b.Property<int>("MenuSort")
                        .HasColumnType("int")
                        .HasColumnName("MenuSort");

                    b.Property<int>("MenuStatus")
                        .HasColumnType("int")
                        .HasColumnName("MenuStatus");

                    b.Property<string>("MenuTarget")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MenuTarget");

                    b.Property<int>("MenuType")
                        .HasColumnType("int")
                        .HasColumnName("MenuType");

                    b.Property<string>("MenuUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MenuUrl");

                    b.Property<long>("Parent")
                        .HasColumnType("bigint")
                        .HasColumnName("Parent");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark");

                    b.HasKey("Id");

                    b.ToTable("tbl_Menu", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.NationalityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Capital");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Currency");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ShortName");

                    b.HasKey("Id");

                    b.ToTable("st_Nationality", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.NextOfKinEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<long>("Employee")
                        .HasColumnType("bigint")
                        .HasColumnName("Employee");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MobileNumber");

                    b.Property<int>("Relationship")
                        .HasColumnType("int")
                        .HasColumnName("Relationship");

                    b.HasKey("Id");

                    b.ToTable("tbl_NextOfKin", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.PaymentHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<string>("NHFNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NHFNumber");

                    b.Property<int>("RRR")
                        .HasColumnType("int")
                        .HasColumnName("RRR");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("TransactionId");

                    b.HasKey("Id");

                    b.ToTable("tbl_PaymentHistory", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.RelationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_Relation", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RoleName");

                    b.Property<int>("RoleSort")
                        .HasColumnType("int")
                        .HasColumnName("RoleSort");

                    b.Property<int>("RoleStatus")
                        .HasColumnType("int")
                        .HasColumnName("RoleStatus");

                    b.HasKey("Id");

                    b.ToTable("tbl_Role", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.SectorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_Sector", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.StateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Capital");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Narration");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nationality");

                    b.HasKey("Id");

                    b.ToTable("st_State", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.SubSectorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("Sector")
                        .HasColumnType("int")
                        .HasColumnName("Sector");

                    b.HasKey("Id");

                    b.ToTable("st_SubSector", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.TitleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("st_Title", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.UserBelongEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<long>("Belong")
                        .HasColumnType("bigint")
                        .HasColumnName("Belong");

                    b.Property<int>("BelongType")
                        .HasColumnType("int")
                        .HasColumnName("BelongType");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<long>("User")
                        .HasColumnType("bigint")
                        .HasColumnName("User");

                    b.HasKey("Id");

                    b.ToTable("tbl_UserBelong", (string)null);
                });

            modelBuilder.Entity("Mortgage.Ecosystem.DataAccess.Layer.Models.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ApiToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApiToken");

                    b.Property<DateTime>("BaseCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("BaseCreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseCreatorId");

                    b.Property<int>("BaseIsDelete")
                        .HasColumnType("int")
                        .HasColumnName("BaseIsDelete");

                    b.Property<long>("BaseModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("BaseModifierId");

                    b.Property<DateTime>("BaseModifyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaseModifyTime");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("int")
                        .HasColumnName("BaseVersion");

                    b.Property<long>("Company")
                        .HasColumnType("bigint")
                        .HasColumnName("Company");

                    b.Property<long>("Employee")
                        .HasColumnType("bigint")
                        .HasColumnName("Employee");

                    b.Property<DateTime>("FirstVisit")
                        .HasColumnType("datetime2")
                        .HasColumnName("FirstVisit");

                    b.Property<int>("IsOnline")
                        .HasColumnType("int")
                        .HasColumnName("IsOnline");

                    b.Property<int>("IsSystem")
                        .HasColumnType("int")
                        .HasColumnName("IsSystem");

                    b.Property<DateTime>("LastVisit")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastVisit");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int")
                        .HasColumnName("LoginCount");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<DateTime>("PreviousVisit")
                        .HasColumnType("datetime2")
                        .HasColumnName("PreviousVisit");

                    b.Property<string>("RealName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RealName");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Salt");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int")
                        .HasColumnName("UserStatus");

                    b.Property<string>("WebToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WebToken");

                    b.HasKey("Id");

                    b.ToTable("tbl_User", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
